# Copyright Contributors to the Open Cluster Management project

language: node_js
node_js: '14'
install: npm ci --no-optional
branches:
    only:
        - main
        - /v*.*.*/
addons:
    sonarcloud:
        organization: 'open-cluster-management'
jobs:
    include:
        - stage: Build & Test
          if: tag IS blank
          script: npm run build && npm test

        - stage: Create Release
          if: type = push AND tag IS blank AND fork = false
          script: scripts/create-release.sh $TRAVIS_COMMIT_MESSAGE

        - stage: Publish NPM Package
          if: tag IS present
          script: scripts/publish-package.sh

        - stage: Publish Storybook
          if: branch = main AND tag IS present
          script: npm run build:storybook
          deploy:
              provider: pages
              skip_cleanup: true
              github_token: $GITHUB_TOKEN
              keep_history: true
              local_dir: storybook-static
              on:
                  branch: main

        - stage: Sonar
          if: branch = main AND tag IS present
          script: npm test && sonar-scanner

        - stage: Automated Dependency Upgrade
          if: type = cron AND branch = main
          install: echo skip install
          script: scripts/update-dependencies.sh
