# Copyright Contributors to the Open Cluster Management project

language: node_js
node_js: '14'
install: npm ci --no-optional
addons:
    sonarcloud:
        organization: 'open-cluster-management'
jobs:
    include:
        - stage: Pull Request
          if: type = pull_request
          script: npm run build && npm test

        - stage: Test - Build - Publish
          if: type = push AND ( branch = main OR branch = /v$.*.*/ ) AND fork = false
          script:
              - set -e # Exit immediately if a command returns a non-zero status.
              - npm test
              - sonar-scanner
              - npm run build
              - npm run build:storybook
              - scripts/create-release.sh $TRAVIS_COMMIT_MESSAGE
              - scripts/publish-package.sh
          deploy:
              provider: pages
              skip_cleanup: true
              github_token: $GITHUB_TOKEN
              keep_history: true
              local_dir: storybook-static
              on:
                  branch: main

        - stage: Automated Dependency Upgrade
          if: type = cron AND branch = main
          install: echo skip install
          script: scripts/update-dependencies.sh
